### ISSUE TITLE
Questions of huge interest in Loki Operator

### ISSUE THREAD

**Issue by xt99** [ViaQ/loki-operator#57]
Hello all,

Let me express great appreciation and hope for this Loki Operator initiative! 

We've been searching for Loki Operator since OKD 4.0 release but with no luck. It's great pleasure to see RedHat's attempts in this direction to bring ELK alternatives to OpenShift 4.x.

Would you mind to give us some timelines when we can expect GA or preview release of Loki Operator? If that will be helpful for you, guys, we're ready to be early testers and adopters of this. 

Also I would like to ask (if this is OK for you) if this Loki Operator will be available in free OKD (unlike current Logging Operator)? Are there any plans of integration of Loki into Cluster Console UI? I think it will be natural and very useful addition to Prometheus integrations there. 

While trying to implement Loki ourselves, we've faced with lack of secure connections between Loki's components. Do you have any plans to make it available out the box (like all other OpenShift's components and Prometheus particularly)? 

Thank you very much for any answers on these subjects!

**Comment by periklis** [comment]
First of all, thanks for stating your interest on the loki operator project. Really appreciate to hear from early adopters! 

Let me try to answer you questions at the best of my ability:
1. We don't have any GA or preview release dates neither for OKD nor for OCP right now. This project aims to provide a kubernetes operator for Loki with out-of-the-box support for OpenShift but w/o requiring the later. The OpenShift integration is part of the OpenShift Cluster Logging stack but an optional thing here. You can follow up the details on this enhancement document: https://github.com/openshift/enhancements/blob/master/enhancements/cluster-logging/loki-storage.md
2. The OpenShift Cluster Logging team is looking into some native integration for logs into the Web Console atm, but this is unrelated to Loki or the current Elasticsearch store. AFAIK the integration is meant to be agnostic of the store, but I don't know much about the details TBH.
3. The path forward for the Loki Operator is to provide in addition to Loki a thin proxy layer to enable integration with user's tenancy and UI desires (e.g. OCP's tenancy model is namespace-driven). Moving forward we look for supporting folks to point their Grafana instance to the operator managed Loki as well as the OpenShift web console.

Last but not least, what are you referring as secure connections between Loki Components? Can you elaborate on the issues you faced on?

Thanks again for dropping by! If you are interested in testing the operator as is right now, I would be glad to provide assistance.

**Comment by jcantrill** [comment]
> Also I would like to ask (if this is OK for you) if this Loki Operator will be available in free OKD (unlike current Logging Operator)? 

This statement is incorrect.  Both the RH cluster-logging-operator and elasticsearch-operator are available to be deployed to OKD.    It may not be as simple as with OCP, but there are no restrictions otherwise.  Any feedback you can provide is welcome.  Please open an issue on the cluster-logging-operator

**Comment by xt99** [comment]
> > Also I would like to ask (if this is OK for you) if this Loki Operator will be available in free OKD (unlike current Logging Operator)?
> 
> This statement is incorrect. Both the RH cluster-logging-operator and elasticsearch-operator are available to be deployed to OKD. It may not be as simple as with OCP, but there are no restrictions otherwise. Any feedback you can provide is welcome. Please open an issue on the cluster-logging-operator

Thanks, @jcantrill, for pointing our attention to this. Official logging stack installation guide (https://docs.openshift.com/container-platform/4.7/logging/cluster-logging-deploying.html) is mentioning operators ("OpenShift Elasticsearch Operator" and "Red Hat OpenShift Logging") which are not present in Operator Hub in OKD: 

<img width="1366" alt="Screenshot 2021-05-27 at 19 12 56" src="https://user-images.githubusercontent.com/608600/119861074-a8187a80-bf1f-11eb-97bb-aa9706e5ff72.png">
<img width="1366" alt="Screenshot 2021-05-27 at 19 13 25" src="https://user-images.githubusercontent.com/608600/119861082-a9e23e00-bf1f-11eb-92a0-58495415a413.png">

This makes us think there is no cluster logging available for OKD. It's a great news if it is! Can you please point us to some guide how to deploy it on OKD (which I'm unable to find)?

**Comment by xt99** [comment]
> First of all, thanks for stating your interest on the loki operator project. Really appreciate to hear from early adopters!
> 
> Let me try to answer you questions at the best of my ability:
> 
> 1. We don't have any GA or preview release dates neither for OKD nor for OCP right now. This project aims to provide a kubernetes operator for Loki with out-of-the-box support for OpenShift but w/o requiring the later. The OpenShift integration is part of the OpenShift Cluster Logging stack but an optional thing here. You can follow up the details on this enhancement document: https://github.com/openshift/enhancements/blob/master/enhancements/cluster-logging/loki-storage.md
> 2. The OpenShift Cluster Logging team is looking into some native integration for logs into the Web Console atm, but this is unrelated to Loki or the current Elasticsearch store. AFAIK the integration is meant to be agnostic of the store, but I don't know much about the details TBH.
> 3. The path forward for the Loki Operator is to provide in addition to Loki a thin proxy layer to enable integration with user's tenancy and UI desires (e.g. OCP's tenancy model is namespace-driven). Moving forward we look for supporting folks to point their Grafana instance to the operator managed Loki as well as the OpenShift web console.
> 
> Last but not least, what are you referring as secure connections between Loki Components? Can you elaborate on the issues you faced on?
> 
> Thanks again for dropping by! If you are interested in testing the operator as is right now, I would be glad to provide assistance.

Thanks, @periklis, for this information! This is very useful and may change our direction of further work.

> what are you referring as secure connections between Loki Components? 
I mean there is no TLS between Promtail and Loki and there is no TLS between Loki and Grafana by default. Also there is no auth between these components. Official Loki docs says "Loki does not come with any included authentication layer. Operators are expected to run an authenticating reverse proxy in front of your services, such as NGINX using basic auth or an OAuth2 proxy" (https://grafana.com/docs/loki/latest/operations/authentication/). So we're wondering how will you deal with this insecurity of Loki.

**Comment by periklis** [comment]
> Thanks, @periklis, for this information! This is very useful and may change our direction of further work.
> 
> > what are you referring as secure connections between Loki Components?
> 
> I mean there is no TLS between Promtail and Loki and there is no TLS between Loki and Grafana by default. Also there is no auth between these components. Official Loki docs says "Loki does not come with any included authentication layer. Operators are expected to run an authenticating reverse proxy in front of your services, such as NGINX using basic auth or an OAuth2 proxy" (https://grafana.com/docs/loki/latest/operations/authentication/). So we're wondering how will you deal with this insecurity of Loki.

We will probably deal with a thin reverse proxy layer as we do on our internal hosted Loki instances, e.g. https://github.com/observatorium/api/
